services:
  restauranttinderfrontend:
    container_name: restauranttinderfrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - restauranttinderbackend
    restart: unless-stopped
    networks:
      - restauranttindernetwork
      - proxy

  restauranttinderbackend:
    container_name: restauranttinderbackend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - restauranttindernetwork

networks:
  restauranttindernetwork:
    driver: bridge
  proxy:
    external: true
    name: proxy
