version: "3.9"
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
     - backend

  backend:
    build: backend
    ports:
      - "3335:3334"
    volumes:
      - ./backend:/app
