FROM node:alpine
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
RUN npm ci
COPY . ./
RUN npm run build

FROM node:alpine
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
RUN npm ci --only=production
COPY --from=0 /app/build .
CMD ["npm", "start"]

